version: 2
jobs:
  build:
    docker:
      - image: bsycorp/kind:latest-1.9
    steps:
      - run:
          name: Waiting for Kubernetes to be ready
          command: |
            until curl -s --fail http://127.0.0.1:10080/kubernetes-ready; do
              sleep 1;
            done
            echo "Kubernetes ready - run tests!"
