version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Start Kubernetes
          command: |
            docker run -d --name kube --privileged -p 8443:8443 -p 10080:10080 bsycorp/kind:latest-1.9
            until curl -s --fail http://127.0.0.1:10080/kubernetes-ready; do
              sleep 1;
            done
            echo "Kubernetes ready - run tests!"
